export const SUCCESS_REGISTER = 'SUCCESS_REGISTER'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const FAIL_REGISTER = 'FAIL_REGISTER'
export const FAIL_LOGIN = 'FAIL_LOGIN'
export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const LOG_OUT = 'LOG_OUT'
export const AUTH_ERROR = 'AUTH_ERROR'
export const USER_LOADED = 'USER_LOADED'
export const USERS_LOADED = 'USERS_LOADED'

export const GET_POSTS = 'GET_POSTS'
export const POSTS_ERROR = 'POSTS_ERROR'
export const ADD_POST = 'ADD_POST'
export const REMOVE_POST = 'REMOVE_POST'
export const UPDATE_POST = 'UPDATE_POST'

export const CLEAR_SEARCH = 'CLEAR_SEARCH'
export const CLEAR_POSTS = 'CLEAR_POSTS'
export const SEARCH_POST = 'SEARCH_POST'
export const CLEAR_EDIT = 'CLEAR_EDIT'
export const EDIT_POST = 'EDIT_POST'
