export const SUCCESS_REGISTER = 'SUCCESS_REGISTER'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const FAIL_REGISTER = 'FAIL_REGISTER'
export const FAIL_LOGIN = 'FAIL_LOGIN'
export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const LOG_OUT = 'LOG_OUT'
export const AUTH_ERROR = 'AUTH_ERROR'
export const USER_LOADED = 'USER_LOADED'
export const USERS_LOADED = 'USERS_LOADED'

export const GET_POSTS = 'GET_POSTS'
export const POSTS_ERROR = 'POSTS_ERROR'
export const ADD_POST = 'ADD_POST'
export const REMOVE_POST = 'REMOVE_POST'
export const UPDATE_POST = 'UPDATE_POST'

export const CLEAR_SEARCH = 'CLEAR_SEARCH'
export const CLEAR_POSTS = 'CLEAR_POSTS'
export const SEARCH_POST = 'SEARCH_POST'
export const CLEAR_EDIT = 'CLEAR_EDIT'
export const EDIT_POST = 'EDIT_POST'


export const GET_COMMENTS = 'GET_COMMENTS'
export const COMMENTS_ERROR = 'COMMENTS_ERROR'
export const ADD_COMMENT = 'ADD_COMMENT'
export const REMOVE_COMMENT = 'REMOVE_COMMENT'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'

export const CLEAR_COMMENTS = 'CLEAR_COMMENTS'
export const SEARCH_COMMENT = 'SEARCH_COMMENT'
export const EDIT_COMMENT = 'EDIT_COMMENT'


export const GET_FRIENDS = 'GET_FRIENDS'
export const FRIENDS_ERROR = 'FRIENDS_ERROR'
export const ADD_FRIEND = 'ADD_FRIEND'
export const REMOVE_FRIEND = 'REMOVE_FRIEND'
export const UPDATE_FRIEND = 'UPDATE_FRIEND'

export const CLEAR_FRIENDS = 'CLEAR_FRIENDS'
export const SEARCH_FRIEND = 'SEARCH_FRIEND'
export const EDIT_FRIEND = 'EDIT_FRIEND'

export const GET_REQUESTS = 'GET_REQUESTS'
export const REQUESTS_ERROR = 'REQUESTS_ERROR'
export const ADD_REQUEST = 'ADD_REQUEST'
export const REMOVE_REQUEST = 'REMOVE_REQUEST'
export const UPDATE_REQUEST = 'UPDATE_REQUEST'

export const CLEAR_REQUESTS = 'CLEAR_REQUESTS'
export const SEARCH_REQUEST = 'SEARCH_REQUEST'
export const EDIT_REQUEST = 'EDIT_REQUEST'
